# Site Info
title: Tony Huang Tech Notes
tagline: 'ARTS weekly blog'
description: 'Algorithm, Reviews, Tips and Shares'
baseurl: ""
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Tony Huang
  description: 'Algorithm, Reviews, Tips and Shares'
  gravatar: 03ce068797689bc04d1b2d99169d4250
  contact:
    linkedin:  https://www.linkedin.com/in/yiyehuang
    github:    https://github.com/YiYeHuang

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics

